//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM1gara.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EnDate { get; set; }
    }
}
